/**
 * OSRS Leagues VI: Demonic Pacts — Pact Node Data
 *
 * Schema per node:
 *   id       {string}   Short identifier matching the in-game tree (e.g. "AA")
 *   name     {string}   Display name
 *   effect   {string}   Full effect description
 *   category {string}   "neutral" | "melee" | "ranged" | "magic"
 *   cost     {number}   Pact Points required (always 1 for now)
 *   tags     {string[]} Optional searchable tags
 *   adjacentTo {string[]} IDs of directly connected nodes in the tree
 *                         (currently partial — will be filled in as tree data is confirmed)
 */

const PACT_CATEGORIES = [
  { id: "neutral", label: "Neutral",  color: "#c8aa6e" },
  { id: "melee",   label: "Melee",    color: "#e04040" },
  { id: "ranged",  label: "Ranged",   color: "#4caf50" },
  { id: "magic",   label: "Magic",    color: "#5ba0e0" },
];

const MAX_PACT_POINTS = 40;

/** Starting node — must be unlocked first before any others. */
const STARTING_NODE_ID = "AA";

const PACTS = [
  // ── Neutral ──────────────────────────────────────────────────────────────
  {
    id: "AA",
    name: "Rune/Ammo Regeneration",
    effect: "50% chance to regenerate runes, ammo, and charges on each use.",
    category: "neutral",
    cost: 1,
    tags: ["regen", "ammo", "runes", "charges", "start"],
    adjacentTo: ["BA", "B1", "B2", "B3"],
  },
  {
    id: "BA",
    name: "Regen Chance Boost",
    effect: "+5% chance to regenerate runes, ammo, and charges.",
    category: "neutral",
    cost: 1,
    tags: ["regen", "ammo", "runes"],
    adjacentTo: ["AA", "CA"],
  },
  {
    id: "CA",
    name: "Accuracy Boost",
    effect: "+15% accuracy in all combat styles.",
    category: "neutral",
    cost: 1,
    tags: ["accuracy"],
    adjacentTo: ["BA", "DA", "F1"],
  },
  {
    id: "DA",
    name: "Defence Boost",
    effect: "+5 permanent Defence level boost.",
    category: "neutral",
    cost: 1,
    tags: ["defence", "level"],
    adjacentTo: ["CA", "F4"],
  },
  {
    id: "F1",
    name: "Major Accuracy",
    effect: "+35% accuracy in all combat styles.",
    category: "neutral",
    cost: 1,
    tags: ["accuracy"],
    adjacentTo: ["CA"],
  },
  {
    id: "F3",
    name: "Regen Chance Upgrade",
    effect: "+30% chance to regenerate runes, ammo, and charges.",
    category: "neutral",
    cost: 1,
    tags: ["regen", "ammo", "runes"],
    adjacentTo: [],
  },
  {
    id: "F4",
    name: "Defence Boost II",
    effect: "+15 permanent Defence level boost.",
    category: "neutral",
    cost: 1,
    tags: ["defence", "level"],
    adjacentTo: ["DA"],
  },
  {
    id: "F13",
    name: "Overheal",
    effect: "Healing with Demonic Pacts overheals you, up to +30% of your base Hitpoints level.",
    category: "neutral",
    cost: 1,
    tags: ["healing", "overheal", "hp", "hitpoints"],
    adjacentTo: [],
  },
  {
    id: "G2",
    name: "Special Attack Efficiency",
    effect: "Special attacks have a 20% chance to not consume any energy.",
    category: "neutral",
    cost: 1,
    tags: ["special attack", "spec", "energy"],
    adjacentTo: ["G4"],
  },
  {
    id: "G4",
    name: "Ranged Energy Restore",
    effect: "Whenever you attack from at least 2 tiles away with any style, restore 2% special attack energy.",
    category: "neutral",
    cost: 1,
    tags: ["special attack", "spec", "energy", "distance", "ranged"],
    adjacentTo: ["G2"],
  },
  {
    id: "H1",
    name: "Distance Accuracy",
    effect: "5% chance per attack to roll max accuracy, increased by 5% per tile of distance.",
    category: "neutral",
    cost: 1,
    tags: ["accuracy", "distance"],
    adjacentTo: ["H4", "H6"],
  },
  {
    id: "H4",
    name: "Off-Hand Boost",
    effect: "While an off-hand item is equipped, gain +5 melee strength, +5 ranged strength, and +2% magic damage.",
    category: "neutral",
    cost: 1,
    tags: ["off-hand", "shield", "melee", "ranged", "magic"],
    adjacentTo: ["H1", "H10"],
  },
  {
    id: "H6",
    name: "Distance Damage Boost",
    effect: "Whenever you max hit from at least 3 tiles away, your next hit from a different style deals +25% damage.",
    category: "neutral",
    cost: 1,
    tags: ["distance", "damage", "hybrid"],
    adjacentTo: ["H1"],
  },
  {
    id: "H10",
    name: "Prayer Penetration",
    effect: "All attacks have +15% Prayer penetration (up to 100%).",
    category: "neutral",
    cost: 1,
    tags: ["prayer", "penetration", "pvp"],
    adjacentTo: ["H4"],
  },
  {
    id: "J1",
    name: "Recoil Scaling",
    effect: "All recoil and Thorns-style effects deal additional damage equal to 1% of your total defence bonuses.",
    category: "neutral",
    cost: 1,
    tags: ["recoil", "thorns", "defence", "damage"],
    adjacentTo: ["J8"],
  },
  {
    id: "J8",
    name: "Zero Damage Recovery",
    effect: "Whenever an attack deals 0 damage to you while a two-handed shield or off-hand is equipped, you're healed for 2.",
    category: "neutral",
    cost: 1,
    tags: ["healing", "shield", "off-hand", "defence"],
    adjacentTo: ["J1"],
  },

  // ── Melee ─────────────────────────────────────────────────────────────────
  {
    id: "B3",
    name: "Melee Minimum Hit",
    effect: "Minimum hit when attacking with a melee weapon is increased by 3, further increased by 3 for each additional tile of distance.",
    category: "melee",
    cost: 1,
    tags: ["melee", "minimum hit", "distance"],
    adjacentTo: ["AA", "D1", "D2"],
  },
  {
    id: "D1",
    name: "Thorns",
    effect: "While a shield is equipped, you gain Thorns — deal 3 melee damage when attacked.",
    category: "melee",
    cost: 1,
    tags: ["thorns", "shield", "recoil", "defence"],
    adjacentTo: ["B3", "G1", "M1"],
  },
  {
    id: "D2",
    name: "Light Weapon Echo",
    effect: "Melee weapons under 1 kg always trigger an additional melee hit using 40% of your base max hit.",
    category: "melee",
    cost: 1,
    tags: ["echo", "light weapon", "1h", "speed"],
    adjacentTo: ["B3", "J2", "G6"],
  },
  {
    id: "D3",
    name: "Blindbag Attack",
    effect: "Each melee attack with a heavy melee weapon (≥1 kg) has a 15% chance to trigger an instant Blindbag attack.",
    category: "melee",
    cost: 1,
    tags: ["blindbag", "heavy weapon", "2h", "proc"],
    adjacentTo: ["D4", "J3", "M3"],
  },
  {
    id: "D4",
    name: "Two-Handed Range",
    effect: "Melee range is doubled whilst using two-handed weapons.",
    category: "melee",
    cost: 1,
    tags: ["2h", "two-handed", "range", "tiles"],
    adjacentTo: ["D3", "M4"],
  },
  {
    id: "G1",
    name: "Reflect Damage",
    effect: "While a shield is equipped, you have a 0.1% chance per Defence level to reflect all damage.",
    category: "melee",
    cost: 1,
    tags: ["shield", "reflect", "defence"],
    adjacentTo: ["D1"],
  },
  {
    id: "G6",
    name: "Light Weapon Strength",
    effect: "Melee weapons under 1 kg or one-handed increase your melee strength by 20% of your Strength level.",
    category: "melee",
    cost: 1,
    tags: ["light weapon", "1h", "strength", "damage"],
    adjacentTo: ["D2"],
  },
  {
    id: "G7",
    name: "Prayer Strength",
    effect: "Melee strength is increased by 50% of your worn prayer bonus.",
    category: "melee",
    cost: 1,
    tags: ["prayer", "strength", "melee", "damage"],
    adjacentTo: [],
  },
  {
    id: "G8",
    name: "Overheal Damage",
    effect: "Attacks with a melee weapon can consume 5 overhealed hitpoints, increasing your minimum hit by 5.",
    category: "melee",
    cost: 1,
    tags: ["overheal", "minimum hit", "melee"],
    adjacentTo: ["F13"],
  },
  {
    id: "G9",
    name: "Two-Handed Ranged Echo",
    effect: "When hitting a target with a two-handed melee weapon, 5% chance to trigger a Ranged echo.",
    category: "melee",
    cost: 1,
    tags: ["2h", "two-handed", "echo", "ranged", "hybrid"],
    adjacentTo: [],
  },
  {
    id: "GA",
    name: "Melee Damage",
    effect: "+1% Melee damage.",
    category: "melee",
    cost: 1,
    tags: ["melee", "damage"],
    adjacentTo: [],
  },
  {
    id: "J2",
    name: "Light Weapon Speed",
    effect: "Melee weapons under 1 kg attack 1 tick (0.6s) faster.",
    category: "melee",
    cost: 1,
    tags: ["light weapon", "speed", "attack speed", "1h"],
    adjacentTo: ["D2"],
  },
  {
    id: "J3",
    name: "Blindbag Upgrade",
    effect: "For each unique heavy melee weapon in your inventory, Blindbag trigger chance is increased by 2% (up to +10%).",
    category: "melee",
    cost: 1,
    tags: ["blindbag", "heavy weapon", "inventory"],
    adjacentTo: ["D3", "M3"],
  },
  {
    id: "J4",
    name: "Distance Damage Scaling",
    effect: "Maximum hit when attacking with a melee weapon is increased by 4%, and an additional 4% per 3 tiles of distance.",
    category: "melee",
    cost: 1,
    tags: ["melee", "distance", "damage", "max hit"],
    adjacentTo: [],
  },
  {
    id: "M1",
    name: "Thorns Double Hit",
    effect: "When Thorns triggers, it always hits twice, dealing 50% damage in the second hit.",
    category: "melee",
    cost: 1,
    tags: ["thorns", "shield", "recoil"],
    adjacentTo: ["D1"],
  },
  {
    id: "M2",
    name: "Weapon Energy Restore",
    effect: "Whenever you deal damage with a melee weapon, restore 2% special attack energy per hit.",
    category: "melee",
    cost: 1,
    tags: ["special attack", "spec", "energy", "melee"],
    adjacentTo: [],
  },
  {
    id: "M3",
    name: "Blindbag Damage",
    effect: "For each unique heavy melee weapon in your inventory, Blindbag max hit is increased by 2% (up to +10%).",
    category: "melee",
    cost: 1,
    tags: ["blindbag", "heavy weapon", "damage", "inventory"],
    adjacentTo: ["D3", "J3"],
  },
  {
    id: "M4",
    name: "Halberd Range",
    effect: "If your melee attack range is at least 4, it is increased to 7.",
    category: "melee",
    cost: 1,
    tags: ["halberd", "range", "tiles", "2h"],
    adjacentTo: ["D4"],
  },

  // ── Ranged ────────────────────────────────────────────────────────────────
  {
    id: "B2",
    name: "Ranged Echo Trigger",
    effect: "Whenever you regenerate ammo, +25% chance to fire a Ranged echo against the enemy.",
    category: "ranged",
    cost: 1,
    tags: ["echo", "ranged", "ammo", "regen"],
    adjacentTo: ["AA", "E1", "E2", "E3", "K10"],
  },
  {
    id: "E1",
    name: "Bow Echo Accuracy",
    effect: "While a bow is equipped, Ranged echoes never miss.",
    category: "ranged",
    cost: 1,
    tags: ["echo", "bow", "accuracy"],
    adjacentTo: ["B2", "K4", "N4", "N5"],
  },
  {
    id: "E2",
    name: "Crossbow Echo Chance",
    effect: "While a crossbow is equipped, +15% chance to trigger Ranged echoes.",
    category: "ranged",
    cost: 1,
    tags: ["echo", "crossbow"],
    adjacentTo: ["B2", "N6", "N7", "K8"],
  },
  {
    id: "E3",
    name: "Thrown Weapon Max Hit",
    effect: "While a thrown weapon is equipped, Ranged echoes have a 20% chance to max hit.",
    category: "ranged",
    cost: 1,
    tags: ["echo", "thrown", "chinchompa", "max hit"],
    adjacentTo: ["B2", "K6", "N8", "N9"],
  },
  {
    id: "HA",
    name: "Ranged Damage",
    effect: "+1% Ranged damage.",
    category: "ranged",
    cost: 1,
    tags: ["ranged", "damage"],
    adjacentTo: [],
  },
  {
    id: "K1",
    name: "Ranged Prayer Boost",
    effect: "Ranged prayers are 30% more effective.",
    category: "ranged",
    cost: 1,
    tags: ["prayer", "ranged", "boost"],
    adjacentTo: [],
  },
  {
    id: "K2",
    name: "Ranged HP Scaling",
    effect: "Ranged strength is increased by 1 for every 10 HP difference between current and max Hitpoints.",
    category: "ranged",
    cost: 1,
    tags: ["ranged", "hp", "hitpoints", "scaling"],
    adjacentTo: [],
  },
  {
    id: "K3",
    name: "Echo Chain",
    effect: "Ranged echoes can now trigger additional Ranged echoes at half your trigger chance (up to 4 times).",
    category: "ranged",
    cost: 1,
    tags: ["echo", "chain", "ranged"],
    adjacentTo: [],
  },
  {
    id: "K4",
    name: "Bow Speed",
    effect: "Bows attack 1 tick (0.6s) faster.",
    category: "ranged",
    cost: 1,
    tags: ["bow", "speed", "attack speed"],
    adjacentTo: ["E1"],
  },
  {
    id: "K6",
    name: "Thrown Weapon Strength",
    effect: "While a thrown weapon is equipped, ranged strength is increased by 80% of your melee strength.",
    category: "ranged",
    cost: 1,
    tags: ["thrown", "strength", "melee", "hybrid"],
    adjacentTo: ["E3"],
  },
  {
    id: "K8",
    name: "Crossbow Power",
    effect: "Crossbows attack 2 ticks (1.2s) slower, but deal +70% damage.",
    category: "ranged",
    cost: 1,
    tags: ["crossbow", "damage", "slow"],
    adjacentTo: ["E2"],
  },
  {
    id: "K10",
    name: "Ammo Echo Chance",
    effect: "Whenever you regenerate ammo, +5% chance to fire a Ranged echo.",
    category: "ranged",
    cost: 1,
    tags: ["echo", "ammo", "regen"],
    adjacentTo: ["B2"],
  },
  {
    id: "N4",
    name: "Bow Minimum Hit",
    effect: "Hitting with a bow increases minimum hit by 1, capping at 15% of base maximum hit.",
    category: "ranged",
    cost: 1,
    tags: ["bow", "minimum hit"],
    adjacentTo: ["E1", "N5"],
  },
  {
    id: "N5",
    name: "Bow Maximum Hit",
    effect: "Hitting with a bow increases maximum hit by 1, capping at 15% of base maximum hit.",
    category: "ranged",
    cost: 1,
    tags: ["bow", "maximum hit", "damage"],
    adjacentTo: ["E1", "N4"],
  },
  {
    id: "N6",
    name: "Crossbow Guaranteed Hit",
    effect: "Crossbow hits always max hit.",
    category: "ranged",
    cost: 1,
    tags: ["crossbow", "max hit", "guaranteed"],
    adjacentTo: ["E2"],
  },
  {
    id: "N7",
    name: "Crossbow Accuracy",
    effect: "Crossbow attacks roll accuracy twice.",
    category: "ranged",
    cost: 1,
    tags: ["crossbow", "accuracy"],
    adjacentTo: ["E2"],
  },
  {
    id: "N8",
    name: "Thrown Weapon Accuracy",
    effect: "While a thrown weapon is equipped, increase ranged accuracy by 60.",
    category: "ranged",
    cost: 1,
    tags: ["thrown", "accuracy"],
    adjacentTo: ["E3"],
  },
  {
    id: "N9",
    name: "Thrown Weapon Multi-Target",
    effect: "When attacking with a thrown weapon, also throw at an additional nearby target.",
    category: "ranged",
    cost: 1,
    tags: ["thrown", "aoe", "multi-target"],
    adjacentTo: ["E3"],
  },

  // ── Magic ─────────────────────────────────────────────────────────────────
  {
    id: "B1",
    name: "Magic Boost",
    effect: "Whenever combat spells regenerate runes, Magic level is boosted by 1 for 30 ticks (18s).",
    category: "magic",
    cost: 1,
    tags: ["magic", "boost", "level", "regen"],
    adjacentTo: ["AA", "C1", "C2", "C3", "C4"],
  },
  {
    id: "C1",
    name: "Air Rune Prayer",
    effect: "Whenever combat spells regenerate air runes, 15% chance to restore 1 prayer point per rune.",
    category: "magic",
    cost: 1,
    tags: ["magic", "air", "prayer", "regen"],
    adjacentTo: ["B1", "I1", "L1", "L5"],
  },
  {
    id: "C2",
    name: "Water Rune Healing",
    effect: "Whenever combat spells regenerate water runes, you're healed for 1 per rune regenerated.",
    category: "magic",
    cost: 1,
    tags: ["magic", "water", "healing", "regen"],
    adjacentTo: ["B1", "I2", "L2", "L6"],
  },
  {
    id: "C3",
    name: "Fire Rune Damage",
    effect: "Whenever combat spells regenerate fire runes, the damage of your next spell hit is increased by 1 per rune.",
    category: "magic",
    cost: 1,
    tags: ["magic", "fire", "damage", "regen"],
    adjacentTo: ["B1", "I3", "L3", "L7"],
  },
  {
    id: "C4",
    name: "Earth Rune Defence",
    effect: "Whenever combat spells regenerate earth runes, Defence level is boosted by 1 per rune for 30 ticks.",
    category: "magic",
    cost: 1,
    tags: ["magic", "earth", "defence", "regen"],
    adjacentTo: ["B1", "I4", "L4", "L8"],
  },
  {
    id: "F5",
    name: "Water Rune Staff",
    effect: "Whenever you regenerate charges from a powered staff or wand, also regenerate 1 water rune.",
    category: "magic",
    cost: 1,
    tags: ["staff", "wand", "water", "regen"],
    adjacentTo: ["F6", "F9", "F10"],
  },
  {
    id: "F6",
    name: "Air Rune Staff",
    effect: "Whenever you regenerate charges from a powered staff or wand, also regenerate 1 air rune.",
    category: "magic",
    cost: 1,
    tags: ["staff", "wand", "air", "regen"],
    adjacentTo: ["F5", "F9", "F10"],
  },
  {
    id: "F7",
    name: "Spell Speed",
    effect: "Attack rate with combat spells from a spellbook is sped up by 2 ticks.",
    category: "magic",
    cost: 1,
    tags: ["magic", "speed", "attack speed", "spellbook"],
    adjacentTo: ["FA"],
  },
  {
    id: "F8",
    name: "Staff Speed",
    effect: "Attack rate with powered staves is sped up by 3 ticks.",
    category: "magic",
    cost: 1,
    tags: ["staff", "speed", "attack speed", "powered staff"],
    adjacentTo: ["FA"],
  },
  {
    id: "F9",
    name: "Earth Rune Staff",
    effect: "Whenever you regenerate charges from a powered staff or wand, also regenerate 1 earth rune.",
    category: "magic",
    cost: 1,
    tags: ["staff", "wand", "earth", "regen"],
    adjacentTo: ["F5", "F6", "F10"],
  },
  {
    id: "F10",
    name: "Fire Rune Staff",
    effect: "Whenever you regenerate charges from a powered staff or wand, also regenerate 1 fire rune.",
    category: "magic",
    cost: 1,
    tags: ["staff", "wand", "fire", "regen"],
    adjacentTo: ["F5", "F6", "F9"],
  },
  {
    id: "FA",
    name: "Magic Damage",
    effect: "+1% Magic damage.",
    category: "magic",
    cost: 1,
    tags: ["magic", "damage"],
    adjacentTo: ["F7", "F8"],
  },
  {
    id: "I1",
    name: "Air Spell Bonus",
    effect: "Air spells deal +7% damage for each active prayer.",
    category: "magic",
    cost: 1,
    tags: ["air", "spell", "prayer", "damage"],
    adjacentTo: ["C1", "L1"],
  },
  {
    id: "I2",
    name: "Water Spell Scaling",
    effect: "Water spells deal increased damage the higher your health percentage (+20% damage at 100% health).",
    category: "magic",
    cost: 1,
    tags: ["water", "spell", "hp", "scaling"],
    adjacentTo: ["C2", "L2"],
  },
  {
    id: "I3",
    name: "Fire Spell Sacrifice",
    effect: "Fire spell casts burn up to 6% of your max Hitpoints to increase damage dealt by double the amount burned.",
    category: "magic",
    cost: 1,
    tags: ["fire", "spell", "sacrifice", "hp", "damage"],
    adjacentTo: ["C3", "L3"],
  },
  {
    id: "I4",
    name: "Earth Spell Debuff",
    effect: "Earth spell hits reduce the enemy's Defence and Magic Defence levels by 2.",
    category: "magic",
    cost: 1,
    tags: ["earth", "spell", "debuff", "defence"],
    adjacentTo: ["C4", "L4"],
  },
  {
    id: "I6",
    name: "Prayer Regeneration",
    effect: "While protection prayers are not active, restore 1 Prayer point every 15 ticks (sped up by 1 tick per 7 prayer bonus).",
    category: "magic",
    cost: 1,
    tags: ["prayer", "restore", "regen"],
    adjacentTo: [],
  },
  {
    id: "L1",
    name: "Air Spell Prayer",
    effect: "Air spells have +1% chance to max hit per 1 prayer bonus, doubled against air-weak enemies.",
    category: "magic",
    cost: 1,
    tags: ["air", "spell", "prayer", "max hit"],
    adjacentTo: ["C1", "I1"],
  },
  {
    id: "L2",
    name: "Water Spell Healing",
    effect: "Water spell hits bounce back to you, healing for 60% of the damage dealt.",
    category: "magic",
    cost: 1,
    tags: ["water", "spell", "healing", "lifesteal"],
    adjacentTo: ["C2", "I2"],
  },
  {
    id: "L3",
    name: "Fire Spell Spread",
    effect: "Fire spell hits apply 1 burn (max 5) and bounce to up to 2 nearby targets.",
    category: "magic",
    cost: 1,
    tags: ["fire", "spell", "aoe", "burn", "spread"],
    adjacentTo: ["C3", "I3"],
  },
  {
    id: "L4",
    name: "Earth Spell Scaling",
    effect: "Earth spells deal additional flat damage based on Defence level (+1 damage per 12 Defence levels).",
    category: "magic",
    cost: 1,
    tags: ["earth", "spell", "defence", "scaling"],
    adjacentTo: ["C4", "I4"],
  },
  {
    id: "L5",
    name: "Smoke Typing",
    effect: "Smoke spells now count as 'air' spells.",
    category: "magic",
    cost: 1,
    tags: ["smoke", "air", "spell type", "ancient"],
    adjacentTo: ["C1"],
  },
  {
    id: "L6",
    name: "Ice Typing",
    effect: "Ice spells now count as 'water' spells.",
    category: "magic",
    cost: 1,
    tags: ["ice", "water", "spell type", "ancient"],
    adjacentTo: ["C2"],
  },
  {
    id: "L7",
    name: "Blood Typing",
    effect: "Blood spells now count as 'fire' spells.",
    category: "magic",
    cost: 1,
    tags: ["blood", "fire", "spell type", "ancient"],
    adjacentTo: ["C3"],
  },
  {
    id: "L8",
    name: "Shadow Typing",
    effect: "Shadow spells now count as 'earth' spells.",
    category: "magic",
    cost: 1,
    tags: ["shadow", "earth", "spell type", "ancient"],
    adjacentTo: ["C4"],
  },
];
